### ISSUE TITLE
Bulk import/export text messages to a text file

### ISSUE THREAD

**Issue by StrikerX3** [tech-ticks/DreamNexus#122]
The leader of a fan translation group requested a few features to facilitate translation work, one of which is the ability to bulk import/export text messages to .txt files.

We already have a script that exports the contents of `message_us.bin` in a human-readable text format in [Scripts/Queries/Rtdx/PrintMessages.csx](https://github.com/tech-ticks/DreamNexus/blob/master/SkyEditor.RomEditor.Rtdx.ConsoleApp/Scripts/Queries/Rtdx/PrintMessages.csx). We could build upon it and add bulk export/import actions to the GUI at some point. Some improvements could be made to it:
- Fix encoding issues (e.g. the é in Pokémon gets corrupted)
- Sort by `TextIdHash` to make the order less random

See [this Discord thread](https://discord.com/channels/886045133311729684/908785818490003516/908785820931076127) for more info.

**Comment by tech-ticks** [comment]
Sorry for taking more than half a year for such a simple feature... I hope this is still somewhat useful at this point. It seems like there might still be some text encoding issues left, but these will hopefully be addresses separately. Strings are sorted by hash names if they're available. Script strings aren't named since they're not contained in the `TextIdHash` enum, but some of these could be extracted from the Lua script files (this isn't done automatically yet).
